version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateWay/Dockerfile

  messageapi:
    image: ${DOCKER_REGISTRY-}messageapi
    build:
      context: .
      dockerfile: MessageApi/Dockerfile


  userapi:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: UserApi/Dockerfile

